version: "3.3"

services:
  static:
    image: testbench/static:0.0.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./sites/conf 
        target: /etc/nginx/conf.d
      - type: bind
        source: ./sites/html
        target: /usr/share/nginx/html
      - type: bind
        source: ./sites/certs
        target: /usr/share/nginx/certs


  sensor:
    image: "testbench/dynamic:0.0.1"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./sensors/html
        target: /root/express/html
      - type: bind
        source: ./sensors/node_modules
        target: /root/express/node_modules

